### ISSUE TITLE
The golden booster

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-organization#26]
Identify improvements from the testing perspective in the Boosters used in OSIO.

#### Tasks
 
- [x] Chicken-egg problem about fabric8-maven-plugin (needs to be called upfront before running the tests, as tests rely on `yml` files generated by the plugin) https://github.com/arquillian/arquillian-organization/issues/34
  - [x] Low hanging fruit: information about a need of running fmp goals beforehand https://github.com/arquillian/arquillian-cube/issues/977
- [ ] Ability to run Cube tests from Che
  - [ ] No information why tests are finished while there is no indication of error (tests seems to be just killed) https://github.com/openshiftio/openshift.io/issues/2152
  - [x] Enable login to OSO from Che to run tests https://github.com/redhat-developer/rh-che/issues/541
- [ ] Improve Cube code base
  - [ ] Potential connection leak https://github.com/arquillian/arquillian-cube/issues/976
  - [x] Authentication settings ignored when running tests https://github.com/arquillian/arquillian-cube/issues/982
  - [x] Improve user experience when running tests in Che https://github.com/arquillian/arquillian-cube/issues/991
- [x] Improve Boosters
  - [x] Cube dependency in boosters - https://github.com/arquillian/arquillian-organization/issues/33 

Other things to investigate:

- [ ] Simplification of the build setup
- [ ] Ability to run Cube tests from build pipeline

**Comment by bartoszmajsak** [comment]
@lordofthejars @dipak-pawar let's make follow-up tasks based on your findings and link back to this story.

**Comment by bartoszmajsak** [comment]
Issue related to username and token propagation in Che https://github.com/redhat-developer/rh-che/issues/541

We might want to chime in and add our use case/reasoning on why this is needed.

**Comment by bartoszmajsak** [comment]
Related issue for prematurely killing test processes ~~~https://github.com/openshiftio/openshift.io/issues/2262~~~ https://github.com/openshiftio/openshift.io/issues/2152

**Comment by dipak-pawar** [comment]
Issues found while testing cube fmp integration `*IT.java` from eclipse che UI.
* `JAVA_HOME` in che when running Junit tests from Che UI https://github.com/eclipse/che/issues/9105
* https://github.com/arquillian/arquillian-cube/issues/1014
