### ISSUE TITLE
Sprint 146 priorities

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-organization#36]
#### Developers experience improvements

- [x] Spike: Integration between Cube and Fabric8-Maven-Plugin  https://github.com/arquillian/arquillian-organization/issues/34

##### Not reached - moved to Sprint 147:

- [ ] Using random ports from portbindings https://github.com/arquillian/arquillian-cube/issues/828
- [ ] Renaming containers so that port remapping may work with wild star operator https://github.com/arquillian/arquillian-cube/pull/847

#### Dependency / Cube versions improvements

- [ ] Update all boosters to use `arquillian-cube-openshift-starter` dependency https://github.com/arquillian/arquillian-organization/issues/35
- [ ] Boosters should use standalone dependency if they are running tests in standalone mode https://github.com/arquillian/arquillian-organization/issues/33

**_Note_**: depending on upstream updates

#### Infrastructure

- [x] Minimal deployment for pilot https://github.com/arquillian/ike-prow-plugins/issues/50
- [x] Error tracking using Sentry https://github.com/arquillian/ike-prow-plugins/issues/30
- [x] Configure junit reporting for Ginkgo tests https://github.com/arquillian/ike-prow-plugins/issues/21

#### Test verification for PRs

- [x] Exclude PRs from test check if they only contain defined type of files https://github.com/arquillian/ike-prow-plugins/issues/23
- [x] Make test detection language specific and configurable https://github.com/arquillian/ike-prow-plugins/issues/1
- [x] Ability to add a comment on the issue when no tests are shipped https://github.com/arquillian/ike-prow-plugins/issues/37
- [x] Regex simplification https://github.com/arquillian/ike-prow-plugins/issues/35

#### Pull Request sanitizer (Not reached - moved to Sprint 147)

- [ ] Description verification https://github.com/arquillian/ike-prow-plugins/issues/5
- [ ] Title verification (semantic messages) https://github.com/arquillian/ike-prow-plugins/issues/6

#### Work-in-progress plugin

- [x] PR status update https://github.com/arquillian/ike-prow-plugins/issues/25

##### Not reached - moved to Sprint 147:
- [ ] Add "work-in-progress" label https://github.com/arquillian/ike-prow-plugins/issues/26
- [ ] Change "WIP" status based on existing label https://github.com/arquillian/ike-prow-plugins/issues/27
- [ ] Configuration https://github.com/arquillian/ike-prow-plugins/issues/28

#### Misc

- [x] Development documentation http://arquillian.org/ike-prow-plugins/

##### Token leak detection plugin

- [ ] https://github.com/arquillian/ike-prow-plugins/issues/22

##### GitHub templates updater 

- [ ] https://github.com/arquillian/ike-prow-plugins/issues/24
