### ISSUE TITLE
Sprint 147 priorities

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-organization#37]
### Arquillian Cube / Boosters improvements (spillover from Sprint 146)

- [x] Using random ports from portbindings https://github.com/arquillian/arquillian-cube/issues/828
- [x] Renaming containers so that port remapping may work with wild star operator [*] https://github.com/arquillian/arquillian-cube/pull/847
- [x] Anything else which comes as SEV-1 from Booster testing (should be opened in https://github.com/arquillian/arquillian-cube/issues upstream repo)

### GitHub automation

- [ ] Ability to trigger plugins on demand https://github.com/arquillian/ike-prow-plugins/issues/61
- [x] Bot name should be configurable https://github.com/arquillian/ike-prow-plugins/issues/55
- [x] Support for inline comment configuration https://github.com/arquillian/ike-prow-plugins/issues/41

#### Test Keeper plugin

- [x] Explain each state of the test-keeper plugin https://github.com/arquillian/ike-prow-plugins/issues/72
- [x] Bypassing test check should be possible for reviewers but not PR creator https://github.com/arquillian/ike-prow-plugins/issues/73
- [x] Only consider addition/modification when checking for test presence https://github.com/arquillian/ike-prow-plugins/issues/71

#### Pull Request sanitizer

- [ ] Title verification (semantic messages) https://github.com/arquillian/ike-prow-plugins/issues/6
- [ ] Description verification https://github.com/arquillian/ike-prow-plugins/issues/5

#### Work-in-progress plugin

- [ ] Configuration https://github.com/arquillian/ike-prow-plugins/issues/28
- [ ] Add "work-in-progress" label https://github.com/arquillian/ike-prow-plugins/issues/26
- [ ] Change "WIP" status based on existing label https://github.com/arquillian/ike-prow-plugins/issues/27

#### Infrastructure

- [ ] Add probes to plugins https://github.com/arquillian/ike-prow-plugins/issues/62
- [ ] Move from pilot phase (tenant deployment) to dsaas https://github.com/arquillian/ike-prow-plugins/issues/68

##### Token leak detection plugin

- [ ] https://github.com/arquillian/ike-prow-plugins/issues/22

##### GitHub templates updater 

- [ ] https://github.com/arquillian/ike-prow-plugins/issues/24
